#!/bin/bash
echo ++[. profile]
export STEVE=$(dirname $(dirname $(readlink ~/.profile)))
export PATH=${PATH}:~/.local/bin
. ${STEVE}/dots/exit_trap.profile
. ${STEVE}/dots/steve.profile
. ~/.profile.errata
. ~/.bashrc
echo --[. profile]
