#!/bin/bash
echo ++[. profile]
export DOTS=$(dirname $(readlink ~/.profile))
export STEVE=$(dirname ${DOTS})
export PATH=${PATH}:~/.local/bin
. ${DOTS}/exit_trap.profile
. ${DOTS}/steve.profile
. ~/.profile.errata
. ~/.bashrc
echo --[. profile]
