#!/bin/bash
echo ++[. profile]
export STEVE=$(dirname $(dirname $(readlink ~/.profile)))
export PATH=${PATH}:~/.local/bin
. ${STEVE}/dots/profile.steve
. ~/.profile.errata
. ~/.bashrc
echo --[. profile]
